# Generated by Django 2.1.5 on 2019-03-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_appliedjobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='people',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
