# Generated by Django 2.1.5 on 2019-04-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='limit_reached',
            field=models.BooleanField(blank='True', default='False'),
        ),
    ]
